spring:
  application:
    name: store

stripe:
  apiUrl: https://api.stripe.com
  TimeOut: 1000
  isEnabled: true
  currencies: USD,KES,GBR

appConfiguration:
  paymentGateway: paypal

emailService:
  host: www.gmail.com
  port: 2071